# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UDIP_Viewer(object):
    def setupUi(self, UDIP_Viewer):
        UDIP_Viewer.setObjectName("UDIP_Viewer")
        UDIP_Viewer.resize(871, 563)
        self.Main = QtWidgets.QWidget(UDIP_Viewer)
        self.Main.setObjectName("Main")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Main)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ControlsBox = QtWidgets.QGroupBox(self.Main)
        self.ControlsBox.setMinimumSize(QtCore.QSize(250, 0))
        self.ControlsBox.setMaximumSize(QtCore.QSize(250, 16777215))
        self.ControlsBox.setObjectName("ControlsBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.ControlsBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.ControlsBox)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.PlotButton = QtWidgets.QPushButton(self.ControlsBox)
        self.PlotButton.setObjectName("PlotButton")
        self.verticalLayout_2.addWidget(self.PlotButton)
        self.horizontalLayout.addWidget(self.ControlsBox)
        self.PlotBox = QtWidgets.QGroupBox(self.Main)
        self.PlotBox.setObjectName("PlotBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.PlotBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.PlotDisplay = MplWidget(self.PlotBox)
        self.PlotDisplay.setObjectName("PlotDisplay")
        self.verticalLayout.addWidget(self.PlotDisplay)
        self.horizontalLayout.addWidget(self.PlotBox)
        UDIP_Viewer.setCentralWidget(self.Main)
        self.menubar = QtWidgets.QMenuBar(UDIP_Viewer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 871, 21))
        self.menubar.setObjectName("menubar")
        UDIP_Viewer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(UDIP_Viewer)
        self.statusbar.setObjectName("statusbar")
        UDIP_Viewer.setStatusBar(self.statusbar)

        self.retranslateUi(UDIP_Viewer)
        QtCore.QMetaObject.connectSlotsByName(UDIP_Viewer)

    def retranslateUi(self, UDIP_Viewer):
        _translate = QtCore.QCoreApplication.translate
        UDIP_Viewer.setWindowTitle(_translate("UDIP_Viewer", "UDIP Viewer"))
        self.ControlsBox.setTitle(_translate("UDIP_Viewer", "Controls"))
        self.label.setText(_translate("UDIP_Viewer", "Test Label (Will be replaced with data controls)"))
        self.PlotButton.setText(_translate("UDIP_Viewer", "Plot"))
        self.PlotBox.setTitle(_translate("UDIP_Viewer", "Plot"))
from mplwidget import MplWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UDIP_Viewer = QtWidgets.QMainWindow()
    ui = Ui_UDIP_Viewer()
    ui.setupUi(UDIP_Viewer)
    UDIP_Viewer.show()
    sys.exit(app.exec_())
